# Generated by Django 4.2.11 on 2025-11-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_alter_itemCode_and_servCode__create_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pre_authorization_required',
            field=models.BooleanField(db_column='preAuthorizationRequired', default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='pre_authorization_required',
            field=models.BooleanField(db_column='preAuthorizationRequired', default=False),
        ),
    ]
